/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "spi_ad9851.h"
#include "stm32f10x.h"

int main(void) {
  SPI_AD9851_Init();

  AD9851_Reset();

  SPI_Cmd(SPI1, ENABLE);

  AD9851_SetFrequency(1000);

  while (1) {
  }
}
