/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f10x.h"
#include "config.h"
#include "ad9851.h"
#include "adc_sample.h"
#include "relay.h"
#include "key.h"
#include "measure.h"
#include "fault_detect.h"
#include "systick_delay.h"
#include "usart_debug.h"
#include <stdio.h>
#include "bsp_ili9341_lcd.h"
#include "bsp_xpt2046_lcd.h"
#include "bsp_panel.h"

typedef enum
{
    APP_MODE_MEASURE = 0, /* 放大电路各项指标检测（报告4.1第一部分） */
    APP_MODE_FAULT        /* 故障检测（报告4.1第二部分） */
} AppMode;

static void PrintMeasureResult(const MeasureResult *r)
{
    int i;
    printf("---- 参数测量 ----\r\n");
    printf("Rin  = %.2f ohm\r\n", r->rin_ohm);
    printf("Rout = %.2f ohm\r\n", r->rout_ohm);
    printf("Gain(1kHz) = %.2f dB\r\n", r->gain_db);
    printf("Cutoff freq = %.1f Hz\r\n", r->cutoff_freq_hz);
    printf("FreqResp:\r\n");
    for (i = 0; i < FREQRESP_POINT_NUM; i++)
    {
        printf("  f=%.0fHz  gain=%.2fdB\r\n",
               r->freqresp[i].freq_hz, r->freqresp[i].gain_db);
    }
}

static void PrintFaultResult(FaultType type)
{
    printf("---- 故障检测 ---- 结果: %s\r\n", FaultDetect_TypeName(type));
}

int main(void)
{
    AppMode mode = APP_MODE_MEASURE;
    MeasureResult baseline;
    MeasureResult cur;

    SysTick_DelayInit();
    USART_Debug_Init(115200);
    AD9851_GPIO_Init();

    /* AD9851_GPIO_Init() 内部已完成 Reset+进入串行模式的一次性脉冲，
     * 但此时40bit寄存器里除了刚写入的那一字节外，其余位仍是上电时的
     * 随机值。按数据手册建议，进入串行模式后应立即写入一次完整的
     * 40bit有效数据以冲掉残留内容，避免误触发掉电模式或工厂测试模式。 */
    AD9851_SetFrequency(TEST_FREQ_HZ);

    ADC_Sample_Init();
    Relay_Init();
    Key_Init();

    printf("System Init Done.\r\n");

    /* 开机时假定电路处于正常状态，先测一次作为故障检测的基准数据
     * （对应报告：故障检测时需要与电路正常运行时的测量数据比较） */
    Delay_ms(200);
    Measure_All(&baseline);
    FaultDetect_SetBaseline(&baseline);
    printf("Baseline captured:\r\n");
    PrintMeasureResult(&baseline);

    ILI9341_Init();
    XPT2046_Init();
    Panel_Init();               /* 画出主菜单 */

    while (1)
    {
        XPT2046_TouchEvenHandler();   /* 建议5~10ms调用一次，可放定时器中断 */

        if (Panel_IsNewSelectionAvailable())
        {
            MEAS_ITEM_t item = Panel_FetchSelection();  /* 取出后自动清"新选择"标志 */

            switch (item)
            {
                case MEAS_INPUT_R:     /* 执行输入电阻测量流程 */        break;
                case MEAS_OUTPUT_R:    /* 执行输出电阻测量流程 */        break;
                case MEAS_GAIN:        /* 执行电压增益测量流程 */        break;
                case MEAS_FREQ_RESP:   /* 执行幅频特性扫描流程 */        break;
                case MEAS_FAULT_R1: case MEAS_FAULT_R2:
                case MEAS_FAULT_R3: case MEAS_FAULT_R4:
                case MEAS_FAULT_C1: case MEAS_FAULT_C2:
                case MEAS_FAULT_C3:    /* 执行对应元件的故障检测流程 */  break;
                default: break;
            }
        }
    }
}
